name: $name
version: $version
main: com.moulberry.axiom.AxiomPaper
description: $description
authors:
  - Moulberry
api-version: "$apiVersion"
permissions:
  axiom.*:
    description: Allows use of all default Axiom features
    default: op

  axiom.entity.*:
    description: Allows use of all entity-related features (spawning, manipulating, deleting)
    default: op
  axiom.entity.spawn:
    description: Allows entity spawning
  axiom.entity.manipulate:
    description: Allows entity manipulation
  axiom.entity.delete:
    description: Allows entity deletion
